if type -q tide
    set --global tide_git_icon ' '

    # Keep Tide's dark, high-contrast backgrounds and change only the hues.
    set --global tide_prompt_color_frame_and_connection '6c7086'
    set --global tide_prompt_color_separator_same_color '7f849c'

    for item in os pwd git status cmd_duration context jobs direnv bun node python rustc java php pulumi ruby go gcloud kubectl distrobox toolbox terraform aws nix_shell crystal elixir zig time
        set --global tide_"$item"_bg_color '303030'
    end

    set --global tide_pwd_color_anchors '89dceb'
    set --global tide_pwd_color_dirs '74c7ec'
    set --global tide_pwd_color_truncated_dirs '7f849c'
    set --global tide_git_bg_color_unstable '303030'
    set --global tide_git_bg_color_urgent '303030'
    set --global tide_git_color_branch 'a6e3a1'
    set --global tide_git_color_dirty 'f9e2af'
    set --global tide_git_color_staged 'f9e2af'
    set --global tide_git_color_untracked '89dceb'
    set --global tide_git_color_conflicted 'f38ba8'
    set --global tide_git_color_operation 'f38ba8'
    set --global tide_git_color_stash 'a6e3a1'
    set --global tide_git_color_upstream 'a6e3a1'
    set --global tide_status_color 'a6e3a1'
    set --global tide_status_color_failure 'f38ba8'
    set --global tide_cmd_duration_color 'f9e2af'
    set --global tide_context_color_default 'fab387'
    set --global tide_context_color_root 'fab387'
    set --global tide_context_color_ssh 'fab387'
    set --global tide_jobs_color 'a6e3a1'
    set --global tide_os_color 'cdd6f4'
    set --global tide_direnv_color 'f38ba8'
    set --global tide_direnv_color_denied 'f38ba8'
    set --global tide_bun_color 'f5c2e7'
    set --global tide_node_color 'a6e3a1'
    set --global tide_python_color '94e2d5'
    set --global tide_rustc_color 'fab387'
    set --global tide_java_color 'fab387'
    set --global tide_php_color '89b4fa'
    set --global tide_docker_color '74c7ec'
    set --global tide_pulumi_color 'f9e2af'
    set --global tide_ruby_color 'eba0ac'
    set --global tide_go_color '89dceb'
    set --global tide_gcloud_color '89b4fa'
    set --global tide_kubectl_color '89b4fa'
    set --global tide_distrobox_color 'cba6f7'
    set --global tide_toolbox_color 'cba6f7'
    set --global tide_terraform_color 'b4befe'
    set --global tide_aws_color 'fab387'
    set --global tide_nix_shell_color '89dceb'
    set --global tide_crystal_color 'f5e0dc'
    set --global tide_elixir_color 'cba6f7'
    set --global tide_zig_color 'fab387'
    set --global tide_time_color 'b4befe'
end
