tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "AdoptOpenJDK/openjdk"
tap "koekeishiya/formulae"

brew "asdf"
brew "deno"
brew "docker", link: false
brew "fish"
brew "ghq"
brew "git"
brew "gnupg"
brew "graphviz"
brew "jq"
brew "mas"
brew "nkf"
brew "pandoc"
brew "peco"
brew "pwgen"
brew "telnet"
brew "terminal-notifier"
brew "watchman"
brew "yarn"
brew "fzf"
brew "gpg"
brew "gawk"
brew "yabai"
brew "skhd"
brew "exa"
brew "ripgrep"
brew "fd"
brew "coreutils"
brew "stow"

cask "adoptopenjdk8"
cask "adoptopenjdk12"
cask "adoptopenjdk"
cask "authy"
cask "dash"
cask "the-unarchiver"
cask "dropbox"
cask "appcleaner"
cask "openinterminal"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
#cask "charles"
cask "notion"
cask "visual-studio-code"
cask "sketch"
cask "docker"
cask "postman"
cask "adobe-creative-cloud"
cask "coteditor"
cask "Karabiner-Elements"
cask "slack"
cask "zoom"

mas "Amphetamine", id:937984704
mas "BetterSnapTool", id: 417375580
mas "Commander One", id: 1035236694
mas "Edison Mail", id: 1489591003
mas "Expressions", id: 913158085
